= Lab 16: Data Masking for Security in Snowflake  
Author: Your Name  
:icons: font  
:source-highlighter: pygments  
:toc: preamble  
:numbered:

== Objective
In this lab, you will configure data masking policies in Snowflake to protect sensitive information such as personally identifiable information (PII).

== Prerequisites
- Snowflake account access with security permissions.

== Steps

1. **Creating a Table with Sensitive Data**
   . Create a table containing sensitive information:
[source,sql]
----
CREATE TABLE customer_data (id INT, name STRING, ssn STRING); 
INSERT INTO customer_data VALUES (1, 'John Doe', '123-45-6789');
----

2. **Creating a Masking Policy**
. Create a masking policy to hide the Social Security Number (SSN):

[source,sql]
----
CREATE MASKING POLICY ssn_mask AS (val STRING) RETURNS STRING -> CASE WHEN CURRENT_ROLE() IN ('SECURITY_ADMIN') THEN val ELSE 'XXX-XX-XXXX' END;
----


3. **Applying the Masking Policy**
. Apply the masking policy to the **ssn** column:

[source,sql]
----
ALTER TABLE customer_data MODIFY COLUMN ssn SET MASKING POLICY ssn_mask;
----


4. **Testing Data Masking**
. Query the table as a non-admin user:

[source,sql]
----
SELECT * FROM customer_data;
----

. Query the table as an admin user:

[source,sql]
----
SELECT * FROM customer_data;
----


== Conclusion
- You have successfully implemented data masking in Snowflake to secure sensitive information based on user roles.

